### ISSUE TITLE
Upgrade template to Next.js 13 app structure

### ISSUE THREAD

**Issue by samueldanso** [Envoy-VC/boilr3#1]

**Comment by envoy1084** [comment]
Hey @samueldanso , working on migrating to app structure.

**Comment by envoy1084** [comment]
Hey @samueldanso , opened a pull request for the app directory. thinking of keeping it in a separate branch because had some issues for migrating. you can check the pull request #2 

would appreciate some feedback

**Comment by envoy1084** [comment]
Deployed to new branch 

https://github.com/Envoy-VC/boilr3/tree/app-dir
